Bookers/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users, controllers:{
  	sessions: 'devise/sessions',
  	registrations: 'devise/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  get "home/about" => "homes#about"
  root to: "homes#top"
  resources :users, only: [:index, :show, :edit, :update]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "search" => "search#search"
end

Bookers/app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id
end

Bookers/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :set_book

	def create
	    favorite = @book.favorites.new(user_id: current_user.id)
	    favorite.save
	end

	def destroy
	    favorite = current_user.favorites.find_by(book_id: @book.id)
	    favorite.destroy
	end

	private
	def set_book
		@book = Book.find(params[:book_id])
	end
end

Bookers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Bookers/app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
		<%= link_to book_favorites_path(book), method: :delete, remote: true do %>
			<i class="fas fa-heart" style="color: red"></i>
			<%= book.favorites.count %>
		<% end %>
<% else %>
		<%= link_to book_favorites_path(book), method: :post, remote: true do %>
			<i class="far fa-heart"></i>
			<%= book.favorites.count %>
		<% end %>
<% end %>

Bookers/app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

Bookers/app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");