Bookers/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users, controllers:{
  	sessions: 'devise/sessions',
  	registrations: 'devise/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  get "home/about" => "homes#about"
  root to: "homes#top"
  resources :users, only: [:index, :show, :edit, :update]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "search" => "search#search"
end

Bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2 , maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  has_many :active_relationships, class_name: "Relationship",foreign_key:"follower_id",dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship",foreign_key:"followed_id",dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def following?(other_user)
    following.include?(other_user)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
        if how_search == "1"
            User.where(['name LIKE ?', "#{search}"])
        elsif how_search == "2"
            User.where(['name LIKE ?', "#{search}%"])
        elsif how_search == "3"
            User.where(['name LIKE ?', "%#{search}"])
        elsif how_search == "4"
            User.where(['name LIKE ?', "%#{search}%"])
        else
            User.all
        end
    end
  end
end

Bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!


  def show
    @user = User.find(params[:id])
  	@book = Book.new
  	@books = @user.books
  end



   def index
    @users = User.all
    @user = current_user
    @book = Book.new
   end

   def new
   end

   def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
   end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
      render :edit
    end
   end

   def following
      @users = User.find(params[:id]).following
   end

   def followers
      @users = User.find(params[:id]).followers
   end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

Bookers/app/helpers/users_helper.rb
module UsersHelper
end

Bookers/app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "フォローする" %>
<% end %>

Bookers/app/views/users/_follow_form.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= render 'unfollow', user: user  %>
  <% else %>
    <%= render 'follow', user: user %>
  <% end %>
<% end %>

Bookers/app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete },remote: true) do |f| %>
  <%= f.submit "フォロー外す"%>
<% end %>

Bookers/app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class = "alert">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
   </div>
<% end %>
<div class="container">
  <div class="row">
    <h2 class="form-header-title">User info</h2>
    <div class="form-body">
      <%= form_for(@user) do |f| %>
        <label for="user_name">Name</label>
        <%= f.text_field :name, autofocus: true %>
        <br>
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        <br>
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, autofocus: true %>
        <br>
        <%= f.submit "Update User" %>
      <% end %>
    </div>
  </div>
</div>

Bookers/app/views/users/followers.html.erb
<div class = "row">
	<h2>Follower Users</h2>
	<% if @users.empty? %>
		<p>ユーザーはいません</p>
	<% else %>
		<table class = "table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan = "3"></th>
				</tr>
			</thead>
			<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %></td>
					<td><%= user.name %></td>
					<td><%= "フォロー数：#{user.following.count}" %></td>
					<td><%= "フォロワー数：#{user.followers.count}" %></td>
					<td><%= link_to 'Show', user_path(user) %></td>
				</tr>
			<% end %>
		</table>
	<%end%>
</div>

Bookers/app/views/users/following.html.erb
<div class = "row">
	<h2>Follow Users</h2>
	<% if @users.empty? %>
		<p>ユーザーはいません</p>
	<% else %>
		<table class = "table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %></td>
					<td><%= user.name %></td>
					<td><%= "フォロー数：#{user.following.count}" %></td>
					<td><%= "フォロワー数：#{user.followers.count}" %></td>
					<td><%= link_to 'Show', user_path(user) %></td>
				</tr>
			<% end %>
		</table>
	<%end%>
</div>

Bookers/app/views/users/index.html.erb
<div class = "row">
<%= render 'books/common_book' ,user:@user,book:@book %>

	<div class = "col-xs-9">
		<h2>Users</h2>
		<table class = "table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan = "4"></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %></td>
						<td><%= user.name %></td>
						<!-- フォロー機能 -->
						<td><%= "フォロー数：#{user.following.count}" %></td>
						<td><%= "フォロワー数：#{user.followers.count}" %></td>
						<td><%= render 'follow_form',user: user %></td>
						<!-- フォロー機能 -->
						<td><%= link_to 'Show', user_path(user) %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

Bookers/app/views/users/show.html.erb
<div class = "row">
<%= render 'books/common_book' ,user:@user,book:@book %>





<div class = "col-xs-9">
	<h2>Books</h2>
	<table class = "table">
			<thead>
				<tr>
					<th colspan = "1"></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan = "1"></th>
				</tr>
			</thead>
			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td><%= link_to user_path(book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book) %></td>
						<td><%= book.body %></td>
						<td><%= "コメント数：#{book.book_comments.count}" %></td>
					</tr>
				<% end %>
			</tbody>
	</table>
</div>