Bookers/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users, controllers:{
  	sessions: 'devise/sessions',
  	registrations: 'devise/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  get "home/about" => "homes#about"
  root to: "homes#top"
  resources :users, only: [:index, :show, :edit, :update]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "search" => "search#search"
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :title,presence: true, length: {maximum: 200}
	validates :body,presence: true, length: {maximum: 200 }

	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
    end

    def Book.search(search, user_or_book, how_search)
  		if user_or_book == "2"
     		if how_search == "1"
            	Book.where(['title LIKE ?', "#{search}"])
        	elsif how_search == "2"
            	Book.where(['title LIKE ?', "#{search}%"])
        	elsif how_search == "3"
            	Book.where(['title LIKE ?', "%#{search}"])
        	elsif how_search == "4"
            	Book.where(['title LIKE ?', "%#{search}%"])
  			else
     			Book.all
  			end
		end
	end
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
       flash[:notice] ="You have creatad book successfully."
  	 redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

	def show
    @book = Book.find(params[:id])
    @user = current_user
    @books = Book.all
    @book_comment = BookComment.new
  end


  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
         flash[:notice] = "You have updated book successfully."
         redirect_to book_path(@book.id)
      else
         render :edit
      end
  end

   def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

	private
  def book_params
  	params.require(:book).permit(:title,:body, :user_id)
  end

end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/views/books/_common_book.html.erb
<div class="col-xs-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 60, 60,fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        <!-- フォロー機能 -->
        <tr>
          <% @user ||= current_user %>
          <th>following</th>
          <th><%= link_to @user.following.count, following_user_path(@user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to @user.followers.count, followers_user_path(@user) %></th>
        </tr>
        <!-- フォロー機能 -->
      </tbody>
    </table>
    <% if user.id == current_user.id %>
      <%= link_to edit_user_path(user) do %>
      <span class = "text-center well glyphicon glyphicon-wrench col-xs-12" aria-hidden="true"></span>
      <% end %>
    <% else %>
      <% if current_user.following?(user) %>
        <%= render 'users/unfollow', user: user %>
      <% else %>
        <%= render 'users/follow', user: user %>
      <% end %>
    <% end %>
    <%= form_for(book,url: books_path) do |f| %>
      <h2>New book</h2>
      <h4>Title</h4>
        <%= f.text_field :title,class: "col-xs-12" %>
        <div style = "margin-top: 40px;">
          <h4>Opinion</h4>
        </div>
          <%= f.text_area :body,class: "col-xs-12" %>
        <br>
        <div  style = "margin-top: 40px;">
          <%= f.submit class:"btn btn-primary col-xs-12" %>
        </div>
    <% end %>
</div>

Bookers/app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class = "alert">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
   </div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>
        <div class="form-header text-center">
        </div>
          <%= form_for(@book) do |f| %>
            <label for="book_title">Title</label>
              <%= f.text_field :title, autofocus: true, class:"form-control", id:"inputEmail"%>
            <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, autofocus: true, class:"form-control", id:"inputEmail"%>
              <div style = "margin-top: 10px;">
                <%= f.submit "Update Book", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
              </div>
              <div style = "margin-top: 10px;">
                <p><%= link_to 'Show', book_path(@book) %>|<%= link_to 'Back', books_path %></p>
              </div>
          <% end %>
    </div>
  </div>
</div>

Bookers/app/views/books/index.html.erb
<% if @book.errors.any? %>
	<div class = "alert">
		<h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
		<ul>
	      <% @book.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	      <% end %>
	    </ul>
	 </div>
<% end %>
<div class = "row">
	<%= render 'books/common_book' ,user: @user,book: @book %>
	<div class = "col-xs-9">
		<h2>Books</h2>
		<table class = "table table-hover ">
			<thead>
				<tr>
					<th colspan = "1"></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan = "2"></th>
				</tr>
			</thead>
			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td><%= link_to user_path(book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book) %></td>
						<td><%= book.body %></td>
						<!-- いいね機能 -->
						<td>
							<div id="favorites_buttons_<%= book.id %>">
								<%= render 'favorites/favorite', book: book %>
							</div>
						</td>
						<!-- いいね機能 -->
						<td><%= "コメント数：#{book.book_comments.count}" %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

Bookers/app/views/books/show.html.erb
<div class = "row">
	<%= render 'books/common_book' ,user:@user,book:Book.new %>
	<div class = "col-xs-9">
		<h2>Book detail</h2>
		<table class = "table">
			<tbody>
				<tr>
					<td><%= link_to user_path(@book.user) do %>
						<%=  attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %>
						<% end %>
						<%= link_to user_path(@book.user) do %>
							<%= @book.user.name  %>
						<% end %>
					</td>
					<td><%= @book.title %></td>
					<td><%= @book.body %></td>
					<% if user_signed_in? && current_user.id == @book.user_id %>
						<td><%= link_to 'Edit',edit_book_path(@book) %></td>
						<td><%= link_to 'Destroy',book_path(@book), method: :delete, data: {confirm: "本当に消しますか" } %></td>
					<% end %>
					<!-- いいね機能 -->
					<td>
						<div id="favorites_buttons_<%= @book.id %>">
							<%= render 'favorites/favorite', book: @book %>
						</div>
					</td>
					<!-- いいね機能 -->
					<td><%= "コメント数：#{@book.book_comments.count}" %></td>
				</tr>

			</tbody>
		</table>
		<!-- コメント一覧　-->
		<table>
			<tbody>
				<% @book.book_comments.each do |book_comment| %>
				<tr>
					<td>
						<%= link_to user_path(book_comment.user) do %>
						<%=  attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %>
						<% end %>
						<br>
						<%= link_to book_comment.user.name,user_path(book_comment.user)  %>
					</td>
					<td><%= book_comment.comment %></td>
					<td>
						<% if book_comment.user == current_user %>
							<%= link_to 'Destroy',book_book_comments_path(book_comment.book,book_comment), method: :delete, data: {confirm: "本当に消しますか" } %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!-- コメント一覧 -->
		<div>
			<%= form_for [@book,@book_comment] do |f| %>
			    <%= f.text_area :comment %>
			  	<%= f.submit %>
			<% end %>
		</div>
	</div>
</div>