Bookers/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users, controllers:{
  	sessions: 'devise/sessions',
  	registrations: 'devise/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  get "home/about" => "homes#about"
  root to: "homes#top"
  resources :users, only: [:index, :show, :edit, :update]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "search" => "search#search"
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :title,presence: true, length: {maximum: 200}
	validates :body,presence: true, length: {maximum: 200 }

	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
    end

    def Book.search(search, user_or_book, how_search)
  		if user_or_book == "2"
     		if how_search == "1"
            	Book.where(['title LIKE ?', "#{search}"])
        	elsif how_search == "2"
            	Book.where(['title LIKE ?', "#{search}%"])
        	elsif how_search == "3"
            	Book.where(['title LIKE ?', "%#{search}"])
        	elsif how_search == "4"
            	Book.where(['title LIKE ?', "%#{search}%"])
  			else
     			Book.all
  			end
		end
	end
end

Bookers/app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

Bookers/app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id
end

Bookers/app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

Bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2 , maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  has_many :active_relationships, class_name: "Relationship",foreign_key:"follower_id",dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship",foreign_key:"followed_id",dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def following?(other_user)
    following.include?(other_user)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
        if how_search == "1"
            User.where(['name LIKE ?', "#{search}"])
        elsif how_search == "2"
            User.where(['name LIKE ?', "#{search}%"])
        elsif how_search == "3"
            User.where(['name LIKE ?', "%#{search}"])
        elsif how_search == "4"
            User.where(['name LIKE ?', "%#{search}%"])
        else
            User.all
        end
    end
  end
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
       flash[:notice] ="You have creatad book successfully."
  	 redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

	def show
    @book = Book.find(params[:id])
    @user = current_user
    @books = Book.all
    @book_comment = BookComment.new
  end


  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
         flash[:notice] = "You have updated book successfully."
         redirect_to book_path(@book.id)
      else
         render :edit
      end
  end

   def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

	private
  def book_params
  	params.require(:book).permit(:title,:body, :user_id)
  end

end

Bookers/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :set_book

	def create
	    favorite = @book.favorites.new(user_id: current_user.id)
	    favorite.save
	end

	def destroy
	    favorite = current_user.favorites.find_by(book_id: @book.id)
	    favorite.destroy
	end

	private
	def set_book
		@book = Book.find(params[:book_id])
	end
end

Bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  	def about
	end

	def top
	end
end

Bookers/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
      @user_or_book = params[:option]
      @how_search = params[:choice]

      if @user_or_book == "1"
        @users = User.search(params[:search], @user_or_book, @how_search)
      else
        @books = Book.search(params[:search], @user_or_book, @how_search)
      end
   end
end

Bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!


  def show
    @user = User.find(params[:id])
  	@book = Book.new
  	@books = @user.books
  end



   def index
    @users = User.all
    @user = current_user
    @book = Book.new
   end

   def new
   end

   def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
   end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
      render :edit
    end
   end

   def following
      @users = User.find(params[:id]).following
   end

   def followers
      @users = User.find(params[:id]).followers
   end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
	def logged_in?
    	!current_user.nil? 
  	end
end

Bookers/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Bookers/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers/app/helpers/non_logins_helper.rb
module NonLoginsHelper
end

Bookers/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

Bookers/app/helpers/search_helper.rb
module SearchHelper
end

Bookers/app/helpers/users_helper.rb
module UsersHelper
end

Bookers/app/views/layouts/_error_form.html.erb
<% if @book.errors.any? %>
	<div class = "alert">
		<h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
		<ul>
	      <% @book.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	      <% end %>
	    </ul>
	 </div>
<% end %>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
      </button>
      <span class = "navbar-left">Bookers</span>
    </div>
    <div class="collapse navbar-collapse" id="navbarEexample7">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="active">
                <div class = "glyphicon glyphicon-home" aria-hidden="true">
                  <%= link_to "Home", user_path(current_user) %>
                </div>
              </li>
              <li class="active">
                <div class = "glyphicon glyphicon-user" aria-hidden="true">
                  <%= link_to "Users", users_path %>
                </div>
              </li>
              <li class="active">
                <div class = "glyphicon glyphicon-book" aria-hidden="true">
                  <%= link_to "Books", books_path %>
                </div>
              </li>
              <li class="active">
                <div class = "glyphicon glyphicon-log-out" aria-hidden="true">
                  <%= link_to "logout", destroy_user_session_path, method: :delete %>
                </div>
              </li>
            <% else %>
              <li class="active">
                <div class = "glyphicon glyphicon-home" aria-hidden="true">
                  <%= link_to "Home", root_path %>
                </div>
              </li>
              <li class="active">
                <div class = "glyphicon glyphicon-link" aria-hidden="true">
                  <%= link_to "About", home_about_path %>
                </div>
              </li>
              <li class="active">
                <div class = "glyphicon glyphicon-edit" aria-hidden="true">
                  <%= link_to "sign up", new_user_registration_path %>
                </div>
              </li>
              <li class="active">
                <div class = "glyphicon glyphicon-log-in" aria-hidden="true">
                  <%= link_to "login", new_user_session_path %>
                </div>
              </li>
            <% end %>
          </ul>
    </div>
  </div>
</nav>

<% flash.each do |message_type, message| %>
  <%= content_tag :div, message, class: message_type %>
<% end %>
  <div class = "container">
    <header>
      <% if logged_in? %>
        <%= form_tag(search_path, :method => 'get') do %>
          <%= text_field_tag :search %>
          <%= select_tag(:option, options_for_select([["User", "1"],["Book","2"]]))%>
          <%= select_tag(:choice, options_for_select([["完全一致", "1" ],["前方一致", "2" ],["後方一致", "3" ],["部分一致", "4" ]])) %>
          <%= submit_tag '検索' %>
        <% end %>
      <% end %>
    </header>
    <%= yield %>
    <footer>
    <p>CopyRight Infratop.inc</p>
    </footer>
  </div>
  </body>
</html>